### ISSUE TITLE
Improvement: hint non exsting TCA

### ISSUE THREAD

**Issue by helsner** [b13/permission-sets#7]
https://github.com/b13/permission-sets/blob/main/Classes/AttachPermissionsToGroups.php#L113

I had a typo in my config causing the whole BE to crash with an invalid foreach input.
Maybe we want to improve that segment in the code by checking the key first and throw a fitting exception to directly display the concrete issue

**Comment by twojtylak** [comment]
The concrete PHP Warning: 
```
Undefined array key "tx_table" in vendor/b13/permission-sets/Classes/AttachPermissionsToGroups.php line 113
```
